### DISCUSSION TITLE
friend/

### DISCUSSION THREAD

**Discussion by giscus** [bluespace3/bluespace3.github.io#3] [Announcements]
# friend/

友情链接

https://bluespace3.github.io/friend/

**Comment by bluespace3** [comment]
## 登陆github评论

**Comment by stitch-top** [comment]
```yml
- name: Dr.626
  url: https://stitch-top.github.io/
  desc: 星星从不会因为自己的光太弱而停止闪耀。
  image: https://stitch-top.github.io/img/image.png
```
